### ISSUE TITLE
dask-cudf+xgboost dmatrix creation fails with JIT_UNSPILL=True 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/dask-cuda#610]
## Bug
dask-cudf+xgboost training fails with `JIT_UNSPILL=True ` . It works with `JIT_UNSPILL=False`. 

#### Cluster Setup
```python
import xgboost as xgb
import dask.array as da
import dask.distributed
from dask_cuda import LocalCUDACluster
import cudf

from dask.utils import parse_bytes
from dask.distributed import Client, wait



cluster = LocalCUDACluster(rmm_pool_size=parse_bytes("25 GB"),
                           scheduler_port=9888,
                           dashboard_address=9787, 
                           jit_unspill=True,
                          )
client = Client(cluster)
```

#### Minimal  Example
```python

# X and y must be Dask dataframes or arrays
num_obs = 1e5
num_features = 20
X = da.random.random(
    size=(num_obs, num_features),
    chunks=(1000, num_features)
)
y = da.random.random(
    size=(num_obs, 1),
    chunks=(1000, 1)
)
X = X.to_dask_dataframe().map_partitions(lambda df:cudf.DataFrame.from_pandas(df))
y = y.to_dask_dataframe().map_partitions(lambda df:cudf.DataFrame.from_pandas(df))

dtrain = xgb.dask.DaskDMatrix(client, X, y)

output = xgb.dask.train(client,
                        {'verbosity': 2,
                         'tree_method': 'hist',
                         'objective': 'reg:squarederror'
                         },
                        dtrain,
                        num_boost_round=4, evals=[(dtrain, 'train')])
```

#### Trace:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-460265854233> in <module>
      1 dtrain = xgb.dask.DaskDMatrix(client, X, y)
      2 
----> 3 output = xgb.dask.train(client,
      4                         {'verbosity': 2,
      5                          'tree_method': 'hist',

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/dask.py in train(client, params, dtrain, num_boost_round, evals, obj, feval, early_stopping_rounds, xgb_model, verbose_eval, callbacks)
    962     client = _xgb_get_client(client)
    963     args = locals()
--> 964     return client.sync(_train_async, global_config=config.get_config(), **args)
    965 
    966 

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    841             return future
    842         else:
--> 843             return sync(
    844                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    845             )

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    351     if error[0]:
    352         typ, exc, tb = error[0]
--> 353         raise exc.with_traceback(tb)
    354     else:
    355         return result[0]

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/distributed/utils.py in f()
    334             if callback_timeout is not None:
    335                 future = asyncio.wait_for(future, callback_timeout)
--> 336             result[0] = yield future
    337         except Exception as exc:
    338             error[0] = sys.exc_info()

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/dask.py in _train_async(client, global_config, params, dtrain, num_boost_round, evals, obj, feval, early_stopping_rounds, verbose_eval, xgb_model, callbacks)
    912             futures.append(f)
    913 
--> 914         results = await client.gather(futures, asynchronous=True)
    915 
    916         return list(filter(lambda ret: ret is not None, results))[0]

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1838                             exc = CancelledError(key)
   1839                         else:
-> 1840                             raise exception.with_traceback(traceback)
   1841                         raise exc
   1842                     if errors == "skip":

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/dask.py in dispatched_train()
    849         worker = distributed.get_worker()
    850         with RabitContext(rabit_args), config.config_context(**global_config):
--> 851             local_dtrain = _dmatrix_from_list_of_parts(**dtrain_ref)
    852             local_evals = []
    853             if evals_ref:

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/dask.py in _dmatrix_from_list_of_parts()
    782     if is_quantile:
    783         return _create_device_quantile_dmatrix(**kwargs)
--> 784     return _create_dmatrix(**kwargs)
    785 
    786 

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/dask.py in _create_dmatrix()
    758 
    759     _data = concat(data)
--> 760     dmatrix = DMatrix(
    761         _data,
    762         _labels,

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/core.py in inner_f()
    431         for k, arg in zip(sig.parameters, args):
    432             kwargs[k] = arg
--> 433         return f(**kwargs)
    434 
    435     return inner_f

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/core.py in __init__()
    536         from .data import dispatch_data_backend
    537 
--> 538         handle, feature_names, feature_types = dispatch_data_backend(
    539             data,
    540             missing=self.missing,

/raid/vjawa/conda/envs/rapids-0.20/lib/python3.8/site-packages/xgboost/data.py in dispatch_data_backend()
    601         return _from_scipy_csr(data, missing, threads, feature_names, feature_types)
    602 
--> 603     raise TypeError('Not supported type for data.' + str(type(data)))
    604 
    605 

TypeError: Not supported type for data.<class 'dask_cudf.core.DataFrame'>
```

### Environment:
```python

dask                      2021.4.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.4.0           pyhd8ed1ab_0    conda-forge
dask-cuda                 0.20.0a210512           py38_38    rapidsai-nightly
dask-cudf                 0.20.0a210512   py38_gbda8457b8b_306    rapidsai-nightly

libxgboost                1.4.0dev.rapidsai0.20      cuda11.2_0    rapidsai-nightly
py-xgboost                1.4.0dev.rapidsai0.20  cuda11.2py38_0    rapidsai-nightly
rapids-xgboost            0.20.0a210507   cuda11.2_py38_g24174d4_329    rapidsai-nightly
xgboost                   1.4.0dev.rapidsai0.20  cuda11.2py38_0    rapidsai-nightly

cudf                      0.20.0a210512   cuda_11.2_py38_gbda8457b8b_306    rapidsai-nightly
cudf_kafka                0.20.0a210512   py38_gbda8457b8b_306    rapidsai-nightly
dask-cudf                 0.20.0a210512   py38_gbda8457b8b_306    rapidsai-nightly
libcudf                   0.20.0a210513   cuda11.2_g4596fe62a0_308    rapidsai-nightly
libcudf_kafka             0.20.0a210512   gcdf09ad255_307    rapidsai-nightly

```

CC: @madsbk

**Comment by quasiben** [comment]
Can you try again with latest dask-cuda ? PR https://github.com/rapidsai/dask-cuda/pull/603 should hopefully resolve this issue.  I don' t think it quite made it into `0.20.0a210512`

**Comment by madsbk** [comment]
The problem is that xgboost uses the name of the type and module to determine appropriate `concat` function to use: 
https://github.com/dmlc/xgboost/blob/6e104f05708536aa4f8806aa3bff7c2082acc3e8/python-package/xgboost/dask.py#L181

```python 
def lazy_isinstance(instance, module, name):
    '''Use string representation to identify a type.'''
    module = type(instance).__module__ == module
    name = type(instance).__name__ == name
    return module and name
```

@VibhuJawa, a workaround you can enable compatibility mode by setting
```
DASK_JIT_UNSPILL_COMPATIBILITY_MODE=True
```

**Comment by VibhuJawa** [comment]
Thanks @madsbk . 

Below indeed fixes the issue. 

```
import os 
os.environ["DASK_JIT_UNSPILL_COMPATIBILITY_MODE"] = 'True'
```

**Comment by trivialfis** [comment]
We got some race conditions when importing modules directly.  If there's a better way to avoid a full import for all possible dependencies please share.  ;-)

**Comment by madsbk** [comment]
> We got some race conditions when importing modules directly. If there's a better way to avoid a full import for all possible dependencies please share. ;-)

I have submitted a small PR that fixes this issue: https://github.com/dmlc/xgboost/pull/6974

**Comment by trivialfis** [comment]
Thanks!  Will review soon.

**Comment by randerzander** [comment]
Are there any performance implications of `os.environ["DASK_JIT_UNSPILL_COMPATIBILITY_MODE"] = 'True'`?

**Comment by madsbk** [comment]
> Are there any performance implications of `os.environ["DASK_JIT_UNSPILL_COMPATIBILITY_MODE"] = 'True'`?

Yes, enabling the compatibility mode will disable some of the performance benefits of JIT-unspill. This is because the compatibility mode unspills all CUDA object inputs before running a task. The only exception (for now) is shuffle where we allow proxy objects explicitly.

Check out the benchmark section of my Dask summit task. It goes though q02, q03, q04, and q21:
https://youtu.be/mHWk7y2p-NM?t=1440
