### ISSUE TITLE
[BUG] dask-cuda workers sometimes enter bad state due to OOM errors rather than restarting

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/dask-cuda#725]
## Reproducer:
1. Do some small memory footprint task (Showing that it works)
2. Do a big task that causes oom to make workers go into bad state
3. Try doing the first small memory task again and show that it fails now (Validating the bad state theory)

## Notebook:
Notebook at [link](https://gist.github.com/VibhuJawa/74424c276c06dc5a38db2e5ecf3dc202) 

I suggest going through the notebook as it contains the `nvidia-smi` output showing that indeed the workers dont restart , have memory allocated as well as the same process ids.  It also is cleanly annotated making the workflow easy to follow  

## MRE: 

```python
import cudf
import dask_cudf
import dask
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import distributed

cluster = LocalCUDACluster()
client = Client(cluster)
```

##### Functions to simulate OOM and normal workflow 

```python
# create_big_cudf_ser -> Causes OOM on a worker
def create_big_cudf_ser():
    n_rows = 150_000_000
    s_1 = cudf.Series([1],dtype='int64').repeat(n_rows)
    s_2 = cudf.Series([1],dtype='int64').repeat(n_rows)
    s_3 = cudf.Series([1],dtype='int64').repeat(n_rows)   
    s_4 = cudf.Series([1],dtype='int64').repeat(n_rows)   
    s_5 = cudf.Series([1],dtype='int64').repeat(n_rows) 
    s_6 = cudf.Series([1],dtype='int64').repeat(n_rows) 
    s_7 = cudf.Series([1],dtype='int64').repeat(n_rows) 
    
    return len(s_1)+len(s_2)+len(s_3)+len(s_4)+len(s_5)+len(s_6)+len(s_7)


#create_small_cudf_ser -> should succeed on a worker
def create_single_cudf_ser():
    n_rows = 200_000_000
    series_1 = cudf.Series([1],dtype='int64').repeat(n_rows)
    return len(series_1)



def schedule_small_tasks():
    n_tasks = 6
    dask_small_array_tasks = [dask.delayed(create_single_cudf_ser)() for i in range(0,n_tasks)]
    outputs = client.compute(dask_small_array_tasks)

    outputs = distributed.wait(outputs)
    completed_tasks = [o.result() for o in outputs.done]
    assert len(completed_tasks) == n_tasks
    print(completed_tasks[0:10])  
    
def schedule_oom_tasks():
    n_tasks = 6
    dask_big_ser_tasks = [dask.delayed(create_big_cudf_ser)() for i in range(0,n_tasks)]
    outputs = client.compute(dask_big_ser_tasks)
    outputs = distributed.wait(outputs)
    completed_tasks = [o.result() for o in outputs.done]
    assert len(completed_tasks) == n_tasks
```

```python
schedule_small_tasks() ### WORKS

schedule_oom_tasks() #### OOMS the worker

schedule_small_tasks() #### Fails now as worker in bad state
```

###  Output Trace:
<details>

```python

[200000000, 200000000, 200000000, 200000000, 200000000, 200000000]


distributed.worker - WARNING - Compute Failed
Function:  create_big_cudf_ser
args:      ()
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory')

distributed.worker - WARNING - Compute Failed
Function:  create_big_cudf_ser
args:      ()
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory')

distributed.worker - WARNING - Compute Failed
Function:  create_big_cudf_ser
args:      ()
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory')

distributed.worker - WARNING - Compute Failed
Function:  create_big_cudf_ser
args:      ()
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory')

distributed.worker - WARNING - Compute Failed
Function:  create_big_cudf_ser
args:      ()
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory')

distributed.worker - WARNING - Compute Failed
Function:  create_big_cudf_ser
args:      ()
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory')

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
/tmp/ipykernel_32917/3054628057.py in <module>
----> 1 schedule_oom_tasks()

/tmp/ipykernel_32917/3329864282.py in schedule_oom_tasks()
     36     outputs = client.compute(dask_big_ser_tasks)
     37     outputs = distributed.wait(outputs)
---> 38     completed_tasks = [o.result() for o in outputs.done]
     39     assert len(completed_tasks) == n_tasks

/tmp/ipykernel_32917/3329864282.py in <listcomp>(.0)
     36     outputs = client.compute(dask_big_ser_tasks)
     37     outputs = distributed.wait(outputs)
---> 38     completed_tasks = [o.result() for o in outputs.done]
     39     assert len(completed_tasks) == n_tasks

/nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/lib/python3.8/site-packages/distributed/client.py in result(self, timeout)
    226         if self.status == "error":
    227             typ, exc, tb = result
--> 228             raise exc.with_traceback(tb)
    229         elif self.status == "cancelled":
    230             raise result

/tmp/ipykernel_32917/3329864282.py in create_big_cudf_ser()
      8     s_5 = cudf.Series([1],dtype='int64').repeat(n_rows)
      9     s_6 = cudf.Series([1],dtype='int64').repeat(n_rows)
---> 10     s_7 = cudf.Series([1],dtype='int64').repeat(n_rows)
     11 
     12     return len(s_1)+len(s_2)+len(s_3)+len(s_4)+len(s_5)+len(s_6)+len(s_7)

/nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/lib/python3.8/site-packages/cudf/core/frame.py in repeat()
   1634             )
   1635 
-> 1636         return self._repeat(repeats)
   1637 
   1638     def _repeat(self, count):

/nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/lib/python3.8/site-packages/cudf/core/frame.py in _repeat()
   1641 
   1642         result = self.__class__._from_table(
-> 1643             libcudf.filling.repeat(self, count)
   1644         )
   1645 

cudf/_lib/filling.pyx in cudf._lib.filling.repeat()

cudf/_lib/filling.pyx in cudf._lib.filling._repeat_via_size_type()

MemoryError: std::bad_alloc: CUDA error at: /nvme/0/vjawa/conda/envs/rapids-21.10-sep-10-dask-sql-gpu-bdb/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory

```

</details>

#### Requested Behaviour:

We should restart the worker when it enters a bad state so that the downstream tasks can succeed. 

CC: @randerzander , @pentschev , @jdye64

**Comment by madsbk** [comment]
Could it have some think to do with running through a Notebook?
The following works for me on DGX15:
```python
import cudf
import dask_cudf
import dask
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import distributed


# create_big_cudf_ser -> Causes OOM on a worker
def create_big_cudf_ser():
    n_rows = 300_000_000
    s_1 = cudf.Series([1], dtype="int64").repeat(n_rows)
    s_2 = cudf.Series([1], dtype="int64").repeat(n_rows)
    s_3 = cudf.Series([1], dtype="int64").repeat(n_rows)
    s_4 = cudf.Series([1], dtype="int64").repeat(n_rows)
    s_5 = cudf.Series([1], dtype="int64").repeat(n_rows)
    s_6 = cudf.Series([1], dtype="int64").repeat(n_rows)
    s_7 = cudf.Series([1], dtype="int64").repeat(n_rows)
    return len(s_1) + len(s_2) + len(s_3) + len(s_4) + len(s_5) + len(s_6) + len(s_7)


# create_small_cudf_ser -> should succeed on a worker
def create_single_cudf_ser():
    n_rows = 200_000_000
    series_1 = cudf.Series([1], dtype="int64").repeat(n_rows)
    return len(series_1)


def schedule_small_tasks():
    n_tasks = 6
    dask_small_array_tasks = [
        dask.delayed(create_single_cudf_ser)() for i in range(0, n_tasks)
    ]
    outputs = client.compute(dask_small_array_tasks)

    outputs = distributed.wait(outputs)
    completed_tasks = [o.result() for o in outputs.done]
    assert len(completed_tasks) == n_tasks
    print(completed_tasks[0:10])


def schedule_oom_tasks():
    n_tasks = 6
    dask_big_ser_tasks = [
        dask.delayed(create_big_cudf_ser)() for i in range(0, n_tasks)
    ]
    outputs = client.compute(dask_big_ser_tasks)
    outputs = distributed.wait(outputs)
    completed_tasks = [o.result() for o in outputs.done]
    assert len(completed_tasks) == n_tasks


if __name__ == "__main__":
    cluster = LocalCUDACluster()
    client = Client(cluster)

    print("*" * 100)
    print("schedule_small_tasks()")
    schedule_small_tasks()  ### WORKS

    try:
        print("*" * 100)
        print("schedule_oom_tasks()")
        schedule_oom_tasks()  #### OOMS the worker
    except:
        pass

    print("*" * 100)
    print("schedule_small_tasks()")
    schedule_small_tasks()  #### Fails now as worker in bad state
    print("*" * 100)
    print("FINISHED")
```

**Comment by randerzander** [comment]
With #9232 closed as out of cudf's control, is there another potential solution?

**Comment by vyasr** [comment]
The solution to the example above is to redefine the function causing the OOM as:
```
def create_big_cudf_ser():
    try:
        n_rows = 300_000_000
        s_1 = cudf.Series([1], dtype="int64").repeat(n_rows)
        s_2 = cudf.Series([1], dtype="int64").repeat(n_rows)
        s_3 = cudf.Series([1], dtype="int64").repeat(n_rows)
        s_4 = cudf.Series([1], dtype="int64").repeat(n_rows)
        s_5 = cudf.Series([1], dtype="int64").repeat(n_rows)
        s_6 = cudf.Series([1], dtype="int64").repeat(n_rows)
        s_7 = cudf.Series([1], dtype="int64").repeat(n_rows)
        return len(s_1) + len(s_2) + len(s_3) + len(s_4) + len(s_5) + len(s_6) + len(s_7)
    except MemoryError as e:
        s_1 = None
        s_2 = None
        s_3 = None
        s_4 = None
        s_5 = None
        s_6 = None
        s_6 = None
        raise
```
That should trigger immediate deletion of any created Series. A similar modification is necessary anywhere that an exception is raised where cleanup of the function-local scope is necessary for the rest of the script to behave as expected.

**Comment by madsbk** [comment]
@VibhuJawa can I ask you to try and see if this fixes the issue: https://github.com/dask/distributed/pull/5338 ?

**Comment by VibhuJawa** [comment]
> @VibhuJawa can I ask you to try and see if this fixes the issue: [dask/distributed#5338](https://github.com/dask/distributed/pull/5338) ?

Spent close to 2 hours of testing various scenarios including cupy with and without pool, cudf with and without pool , various cluster sizes and was never able to get the worker in a bad state. 

Can confirm that with https://github.com/dask/distributed/pull/5338 seems to fix all the scenrrios i could think of and text. Thanks a ton for working on the issue @madsbk  !!!

**Comment by madsbk** [comment]
Thanks @VibhuJawa

**Comment by randerzander** [comment]
Closed by dask/distributed#5338
